
version: 2

# WARNING: generated file, use update.py for updates

# Multiple directories not working properly
# See https://github.com/dependabot/dependabot-core/issues/2178

updates:


  - package-ecosystem: docker
    directory: /buildenv-openjdk8-with-ant-gcc
    schedule:
      interval: weekly

