
name: _ Image building helpers

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      push:
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load configuration and versions
        run: cat version.rc >> "$GITHUB_ENV"

      - name: Run update.py and check no files were modified
        run: ./update.py && git diff --exit-code .

      - name: Log into image registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:buildenv-${{ inputs.name }}"
          push: ${{ inputs.push }}
          tags: "${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REGISTRY_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_VERSION_TAG }}-${{ inputs.name }}"
